spring.application.name=app
spring.datasource.url=jdbc:mysql://localhost:3306/pitos
spring.datasource.username=pitos
spring.datasource.password=pitos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#server.servlet.context-path=/app1

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
